version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python 3.9 and dependencies"
      - curl -sS https://bootstrap.pypa.io/get-pip.py | python3
      - python3 -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install selenium
      - pip install pytest pytest-html
      - pip install --upgrade webdriver_manager
      - echo "Dependencies installed successfully"

  build:
    commands:
      - echo "Starting tests"
      - cd tests
      - pytest test_change_sign_tag_size.py -v -s


