version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python 3.9 and dependencies"
      - wget "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" -O firefox.tar.bz2
      - tar -xjf firefox.tar.bz2
      - sudo mv firefox /opt/
      - sudo ln -s /opt/firefox/firefox /usr/bin/firefox
      - firefox --version
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - sudo yum localinstall google-chrome-stable_current_x86_64.rpm -y
      - google-chrome --version
      - echo "Installing Microsoft Edge browser"
      - sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
      - sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/edge
      - sudo dnf install microsoft-edge-stable -y
      - microsoft-edge --version
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - sudo python3 get-pip.py
      - pip3 install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - sudo yum install git -y
      - git clone "https://github.com/Alampurthanvi/Docusign_sample.git"
      - pip install -r Docusign_sample/requirements.txt
      - pip install --upgrade numpy pandas
      - echo "Dependencies installed successfully"

  build:
    commands:
      - echo "Starting tests"
      - cd tests
      - pytest test_create_new_user.py -v -s
